# Start your image with a node base image
FROM php:8.1-cli
FROM bitnami/laravel:10.10
FROM composer:2.6.6
FROM mariadb:11.0

# The /app directory should act as the main application directory
WORKDIR /

# Copy the app package and package-lock.json file
COPY composer*.json ./

# Copy local directories to the current local directory of our docker image (/app)

# Install node packages, install serve, build the app, and remove dependencies at the end
RUN composer install \
    && php artisan key:generate \
EXPOSE 8000

# Start the app using serve command
CMD [ "php artisan serve"]